#!/bin/bash

CAP=$2
SSID=$3

command -v aircrack-ng > /dev/null 2>&1 || { echo "I require aircrack-ng but it's not installed.  Aborting." >&2; exit 1; }

crackloop () {
	for wl in $(ls *txt.bz2|sort -k 8); do
	    echo "$wl" >> $PWD/wordlist-in-use.log
	    echo "Using wordlist:" "$wl"
	    bzcat "$wl" | aircrack-ng -q $PWD/"$CAP" -l $PWD/aircrack-results.log -b "$SSID" -w- && \
	    	rm $wl
	done
}

 
"$@"
